//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetRGR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=DotNetRGR;Integrated Security=True")]
        public string DotNetRGRConnectionString {
            get {
                return ((string)(this["DotNetRGRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=netrgr;Integrated Security=True")]
        public string netrgrConnectionString {
            get {
                return ((string)(this["netrgrConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=dotnet11;Integrated Security=True")]
        public string dotnet11ConnectionString {
            get {
                return ((string)(this["dotnet11ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=drgr;Integrated Security=True")]
        public string drgrConnectionString {
            get {
                return ((string)(this["drgrConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=lab3;Integrated Security=True")]
        public string lab3ConnectionString {
            get {
                return ((string)(this["lab3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2CBA74H;Initial Catalog=\"C:\\USERS\\ATTOKTIST\\DOCUMENTS\\VISUAL " +
            "STUDIO 2015\\PROJECTS\\DOTNET15\\DOTNET15\\APP_DATA\\DOTNET11.MDF\";Integrated Securit" +
            "y=True")]
        public string C__USERS_ATTOKTIST_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_DOTNET15_DOTNET15_APP_DATA_DOTNET11_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_ATTOKTIST_DOCUMENTS_VISUAL_STUDIO_2015_PROJECTS_DOTNET15_DOTNET15_APP_DA" +
                    "TA_DOTNET11_MDFConnectionString"]));
            }
        }
    }
}
